name: unpub_auth
description: A cli used to refresh googleapis token.
version: 0.0.1
homepage: https://github.com/bytedance/unpub

environment:
  sdk: '>=2.15.0 <3.0.0'

executables:
  unpub_auth:

dependencies:
  collection: ^1.15.0
  googleapis_auth: ^1.3.0
  path: ^1.8.1
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
